In [2]:
import pandas as pd
import numpy as np
import datetime as dt
from pathlib import Path
from datetime import datetime, timedelta
%matplotlib inline

In [36]:
source_master = Path("Resources/complete_master.csv")
master_df = pd.read_csv(source_master)
source_apple = Path("Resources/master_apple.csv")
source_amd = Path("Resources/master_amd.csv")
source_msft = Path("Resources/master_msft.csv")
source_tsla = Path("Resources/master_tesla.csv")
tsla_df = pd.read_csv(source_tsla)

apple_df = pd.read_csv(source_apple)
amd_df = pd.read_csv(source_amd)
msft_df = pd.read_csv(source_msft)

,Unnamed: 0,OptionKey,Symbol,ExpirationDate,AskPrice,AskSize,BidPrice,BidSize,LastPrice,PutCall,StrikePrice,Volume,OpenInterest,UnderlyingPrice,DataDate
0,528658,MSFT2019-08-02C124.002019-06-20,MSFT,2019-08-02,14.60,21,13.85,18,13.79,call,124.0,1,0,136.95,2019-06-20
1,528659,MSFT2019-08-02C125.002019-06-20,MSFT,2019-08-02,13.35,13,12.95,2,12.32,call,125.0,1,6,136.95,2019-06-20
2,528661,MSFT2019-08-02C127.002019-06-20,MSFT,2019-08-02,11.60,13,11.15,3,11.37,call,127.0,25,15,136.95,2019-06-20
3,528664,MSFT2019-08-02C130.002019-06-20,MSFT,2019-08-02,9.05,9,8.85,12,9.15,call,130.0,4,62,136.95,2019-06-20
4,528665,MSFT2019-08-02C131.002019-06-20,MSFT,2019-08-02,8.40,12,8.00,10,7.50,call,131.0,40,103,136.95,2019-06-20

In [22]:
msft_df['ExpirationDate'] =  pd.to_datetime(msft_df['ExpirationDate'], infer_datetime_format=True)
msft_df['DataDate'] =  pd.to_datetime(msft_df['DataDate'], infer_datetime_format=True)
msft_df['time delta'] = msft_df['ExpirationDate'] - msft_df['DataDate']
msft_df['% out'] = msft_df['StrikePrice'] / msft_df['UnderlyingPrice'] - 1

In [33]:
apple_df['ExpirationDate'] =  pd.to_datetime(apple_df['ExpirationDate'], infer_datetime_format=True)
apple_df['DataDate'] =  pd.to_datetime(apple_df['DataDate'], infer_datetime_format=True)
apple_df['time delta'] = apple_df['ExpirationDate'] - apple_df['DataDate']
apple_df['% out'] = apple_df['StrikePrice'] / apple_df['UnderlyingPrice'] - 1

In [34]:
amd_df['ExpirationDate'] =  pd.to_datetime(amd_df['ExpirationDate'], infer_datetime_format=True)
amd_df['DataDate'] =  pd.to_datetime(amd_df['DataDate'], infer_datetime_format=True)
amd_df['time delta'] = amd_df['ExpirationDate'] - amd_df['DataDate']
amd_df['% out'] = amd_df['StrikePrice'] / amd_df['UnderlyingPrice'] - 1

In [37]:
tsla_df['ExpirationDate'] =  pd.to_datetime(tsla_df['ExpirationDate'], infer_datetime_format=True)
tsla_df['DataDate'] =  pd.to_datetime(apple_df['DataDate'], infer_datetime_format=True)
tsla_df['time delta'] = tsla_df['ExpirationDate'] - tsla_df['DataDate']
tsla_df['% out'] = tsla_df['StrikePrice'] / tsla_df['UnderlyingPrice'] - 1